### ISSUE TITLE
how to set the data path?

### ISSUE THREAD

**Issue by SeekPoint** [reedscot/cvpr2016#2]
In train_cub_hybrid.sh:
th train_sje_hybrid.lua \
  -data_dir data/cub \
  -image_dir images \
  -ids_file trainvalids.txt \

after I uncompress 'cub_txt.tar.gz', I got a dictrectory 'cub_txt' which I suppose it should be set to   -data_dir data
but what 's for   -image_dir images and   -ids_file trainvalids.txt ?

**Comment by reedscot** [comment]
Did you download from https://docs.google.com/uc?id=0B0ywwgffWnLLZW9uVHNjb2JmNlE&export=download ?

When I uncompress that, here is what I see:

`$ ls`
allclasses.txt      manifest.txt        trainids.txt        valids.txt
bow_c10         testclasses.txt     trainvalclasses.txt vocab_c10.t7
cvpr2016_cub.tar.gz text_c10        trainvalids.txt     w2v_c10
images          trainclasses.txt    valclasses.txt      word_c10

**Comment by SeekPoint** [comment]
solved and thanks!
