### ISSUE TITLE
Is Description Data Set Available to Research Community?

### ISSUE THREAD

**Issue by sandareka** [reedscot/cvpr2016#6]
Hi, 

May I please if the descriptions data set you have used for this project is available for research community for use of research and study work? If you can make it available we will be really grateful. 

Thank you in advance!

**Comment by shikhar-scs** [comment]
@reedscot ?

**Comment by shikhar-scs** [comment]
Here https://drive.google.com/file/d/0B0ywwgffWnLLcms2WWJQRFNSWXM/view
